SVD using numpy

In [1]:
#SVD using numpy
import numpy as np
from numpy.linalg import svd

In [2]:
#Define your matrix as a 2D numpy array
A = np.array([[4,0],[3,-5]])
U,S,VT = svd(A)

In [4]:
print('left singular vectors: ')
print(U)
print('\nsingular values: ')
print(np.diag(S))
print('\nright singular vectors: ')
print(VT)

left singular vectors: 
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]

singular values: 
[[6.32455532 0.        ]
 [0.         3.16227766]]

right singular vectors: 
[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [5]:
#check that this is an exact decomposition
#@ is used for multiplication
print(U@np.diag(S)@VT)

[[ 4.00000000e+00 -1.11022302e-15]
 [ 3.00000000e+00 -5.00000000e+00]]


In [18]:
#second matrix
#add dummy rows and make all matrix 3 by 3
B = np.array([[3,-3,2],[3,0,-3],[0,0,0]])
U,S,VT = svd(B)

In [19]:
print('left singular vectors: ')
print(U)
print('\nsingular values: ')
print(np.diag(S))
print('\nright singular vectors: ')
print(VT)

left singular vectors: 
[[-0.8816746  -0.47185793  0.        ]
 [-0.47185793  0.8816746   0.        ]
 [ 0.          0.          1.        ]]

singular values: 
[[ 4.85855444  0.          0.        ]
 [ 0.          4.04900589  0.        ]
 [ 0.          0.         -0.        ]]

right singular vectors: 
[[-0.83576249  0.54440551 -0.07158002]
 [ 0.30364244  0.3496102  -0.88632611]
 [-0.45749571 -0.76249285 -0.45749571]]


In [20]:
#check that this is an exact decomposition
#@ is used for multiplication
print(U@np.diag(S)@VT)

[[ 3.0000000e+00 -3.0000000e+00  2.0000000e+00]
 [ 3.0000000e+00  8.8817842e-16 -3.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]


In [24]:
#third matrix
#add dummy rows and make all matrix 3 by 3
C = np.array([[4,3,0],[2,4,0],[0,-2,0]])
U,S,VT = svd(C)

In [25]:
print('left singular vectors: ')
print(U)
print('\nsingular values: ')
print(np.diag(S))
print('\nright singular vectors: ')
print(VT)

left singular vectors: 
[[-0.72171131  0.62469505 -0.2981424 ]
 [-0.65186828 -0.46852129  0.59628479]
 [ 0.2328101   0.62469505  0.74535599]]

singular values: 
[[6.70820393 0.         0.        ]
 [0.         2.         0.        ]
 [0.         0.         0.        ]]

right singular vectors: 
[[-0.62469505 -0.78086881 -0.        ]
 [ 0.78086881 -0.62469505 -0.        ]
 [ 0.          0.          1.        ]]


In [26]:
#check that this is an exact decomposition
#@ is used for multiplication
print(U@np.diag(S)@VT)

[[ 4.00000000e+00  3.00000000e+00  0.00000000e+00]
 [ 2.00000000e+00  4.00000000e+00  0.00000000e+00]
 [-2.22044605e-16 -2.00000000e+00  0.00000000e+00]]


SVD using sklearn

In [32]:
from sklearn.decomposition import TruncatedSVD
D=np.array([[-1,2,0],[2,0,-2],[0,-2,1]])
print('original matrix: ')
D

original matrix: 


array([[-1,  2,  0],
       [ 2,  0, -2],
       [ 0, -2,  1]])

In [35]:
svd = TruncatedSVD(n_components = 2)
D_transf = svd.fit_transform(D)
print('Transformed matrix after reducing to 2 features:')
print(D_transf)

Transformed matrix after reducing to 2 features:
[[-1.80245534 -1.32331203]
 [ 2.30895658 -1.6336216 ]
 [ 0.64797706  2.14012283]]


In [36]:
print('singular values:')
print(svd.singular_values_)

singular values:
[3. 3.]
